app:
  telegram-token: ${APP_TELEGRAM_TOKEN}
  url_client:
    scrapper_default_url: http://localhost:8080
  retry:
    max-attempts: 3
    retry-delay: 5


spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
